application: greedgamealex
version: 1
runtime: go
api_version: go1.9

threadsafe: yes

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "1h"

- url: /play
  static_dir: ionic-app
  expiration: "1m"
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: _go_app